### ISSUE TITLE
clean up variable names in both spatial and weather data

### ISSUE THREAD

**Issue by beanumber** [beanumber/macleish#15]

**Comment by liwencong1995** [comment]
What do this two variables mean in the data collected by OrchardMet?
PAR_Den_Avg
PAR_Tot_Avg

**Comment by liwencong1995** [comment]
PAR_Den_Avg = Photosynthetically Active Radiation (sunlight between 400 and 700 nm) in average density of Watts per meter squared
PAR_Tot_Avg = Photosynthetically Active Radiation (sunlight between 400 and 700 nm) in average total over measurement period of Watts per meter squared

I have updated this two variables in doucumentation.
