### ISSUE TITLE
upcoming sf breaks macleish on CRAN

### ISSUE THREAD

**Issue by edzer** [beanumber/macleish#26]
See
* https://www.r-spatial.org/r/2020/03/17/wkt.html and
* https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt

One of your tests tests for the legacy contents of a `crs` object, which breaks with upcoming sf. Please modify (or remove) the test and resubmit to CRAN to avoid error resulting from sf updates.

**Comment by rsbivand** [comment]
Error is, as CRAN errors:

```
* checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  Reading layer `CONTOURS250K_ARC' from data source `/tmp/RtmplxQBcm/contours250k' using driver `ESRI Shapefile'
  Simple feature collection with 50395 features and 3 fields
  geometry type:  LINESTRING
  dimension:      XY
  bbox:           xmin: 33874.42 ymin: 778055.9 xmax: 325713.8 ymax: 959744.8
  projected CRS:  NAD83 / Massachusetts Mainland
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 9 | SKIPPED: 0 | WARNINGS: 1 | FAILED: 3 ]
  1. Error: data integrity (@test-macleish.R#11) 
  2. Error: data integrity (@test-macleish.R#6) 
  3. Error: (unknown) (@test-macleish.R#6) 
  
  Error: testthat unit tests failed
  Execution halted
```

**Comment by beanumber** [comment]
Thanks! I think I've fixed the error on GitHub, but my Rhub build is still failing on some platforms. 

I don't think it's an `sf` problem, but I am kind of stumped: 

https://builder.r-hub.io/status/macleish_0.3.5.tar.gz-6a9bd79ab21d452fb9ad857918b4f813

The error is:

```
Error in loadNamespace(name) : there is no package called ‘BiocManager’
```

But I don't know why `BiocManager` would be necessary at all.

**Comment by rsbivand** [comment]
No idea,  do not use rhub at all. Something must think that some BioConductor package is required, which  would then be installed using the missing package. That package is on CRAN, so possibly a random error/outage. If you can attach me (roger.bivand@nhh.no) a tarball (just R CMD build output), I can test locally if you like. **remotes** has no facility for just building a package, I think.

**Comment by edzer** [comment]
r-hub tries to load this before even looking at the dependencies of macleish, so this is an r-hub related issue.

**Comment by beanumber** [comment]
OK. I submitted a revision to CRAN last week, and this came back:

https://win-builder.r-project.org/incoming_pretest/macleish_0.3.5_20200327_174156/Windows/00check.log

I know that R 4.0 is changing the default behavior of `stringsAsFactors`, but I am not using this.
