### ISSUE TITLE
consider refactoring spatial data

### ISSUE THREAD

**Issue by beanumber** [beanumber/macleish#27]
Currently, the spatial data is contained within the package as a `list` of 12 `sf` objects. Perhaps it would be easier to simply have 12 `sf` objects presented by the package. That might also facilitate better documentation. 

Each layer should be called `macleish_x`, where `x` is the layer name. (Or something similar.)

**Comment by nicholasjhorton** [comment]
what's your proposed timeframe?  Would this be before September 15th?

**Comment by beanumber** [comment]
Let's not do that. I'm just recording ideas here for @rudeboybert 's class

**Comment by beanumber** [comment]
Let's leave the `macleish_layers` list for backwards compatibility.
