### ISSUE TITLE
update maple sap data

### ISSUE THREAD

**Issue by beanumber** [beanumber/macleish#29]
The most recent data is from 2017. Reid Bertone-Johnson (Landscape Studies) should have any new data. 

``` r
library(macleish)
#> Loading required package: etl
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
maple_sap %>% arrange(desc(when))
#> # A tibble: 118 x 4
#>    when         sap Comments People       
#>    <date>     <dbl> <chr>    <chr>        
#>  1 2017-03-21  17   <NA>     Paul         
#>  2 2017-03-20  17   <NA>     <NA>         
#>  3 2017-03-10  17   <NA>     Molly Day    
#>  4 2017-03-08  16.5 <NA>     Molly Day    
#>  5 2017-03-06  NA   <NA>     Lucy         
#>  6 2017-03-02   7   <NA>     Paul         
#>  7 2017-03-01  12   <NA>     Paul & Eva AM
#>  8 2017-02-28  32   <NA>     Paul AM      
#>  9 2017-02-27  12   <NA>     Lucy         
#> 10 2017-02-26   7   <NA>     Paul         
#> # … with 108 more rows
```

<sup>Created on 2020-08-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by rudeboybert** [comment]
* Start with `foofactors` demo video. There should be a segment 
* Then skim chapters on how to add data to package https://r-pkgs.org/data.html and then how to update (if necessary) help https://r-pkgs.org/man.html
* Create a new `update-maple-data` branch off of `SURF2021` branch
* Then actually do it

**Comment by djkelly00** [comment]
Reid Bertone-Johnson is no longer the manager of MacLeish. Paul Wetzel reported that after 2017, no maple sap data was updated. In 2018, MacLeish didn't measure the sap. In 2019 and 2020, no sap was collected.

**Comment by beanumber** [comment]
Thanks for looking into this @djkelly00
