### ISSUE TITLE
Add references as literature review

### ISSUE THREAD

**Issue by rudeboybert** [beanumber/macleish#42]
- [x] Add PDF's sent by Paul via email to `vignettes/Paper/references/` folder
- [x] In introduction/background, add all journal articles to `paper.bib` BibTeX bibliography file and add reference to them in Paper.Rmd. For example to add Binney 2008, add `@Binney:2008` to Rmd and see what changes

**Comment by djkelly00** [comment]
@rudeboybert Hi Bert, I just finished updating the references. I figured out how to get the url link to work in the references. Let me know what you think about the introduction. Paul sent me a forest management plan that elaborates on MacLeish overview and regional significance that I could potentially add to the introduction. Thank you!

**Comment by rudeboybert** [comment]
Thanks for doing this! The first pass of the intro is 🎯🎯🎯. closing this
