### ISSUE TITLE
Start completing package functionality subsections

### ISSUE THREAD

**Issue by rudeboybert** [beanumber/macleish#44]
- [x] Maps of MacLeish 
- [x] Two plot datasets on change in tree diameter in Hemlock Woolly Adelgid dominated areas 
- [x] Weather data
    - Use of 2015 weather data from both Whately and Orchard weather stations 
    - Live weather readings from Whately and Orchard weather stations 
- [x] PhenoCam functions

**Comment by djkelly00** [comment]
Hi @rudeboybert, I'm experiencing an issue at line 99 due to the following error: 

'Error in glimpse(tree_diameter1) : object 'tree_diameter1' not found calls: <Anonymous> ... withCallingHandlers -> withvisisble -> eval -> eval -> glimpse Execution halted'

**Comment by rudeboybert** [comment]
Hey @djkelly00 check out my comment I posted here: https://github.com/beanumber/macleish/commit/0eaa33620bf19f601d0890bf6c279ebf2f40df4a. the manuscripts compiles on my end now
