### ISSUE TITLE
send inquiry to JOSS

### ISSUE THREAD

**Issue by beanumber** [beanumber/macleish#53]
After reading the [JOSS submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html), I think we have a reasonable chance of success. Our case will be stronger if we can get some evidence of research utility. Does Jesse Bellemare have any papers published that use these data? 

I see [JOSE](https://jose.theoj.org/about) as a backup option if JOSS doesn't work out. 

@rudeboybert what do you think?

**Comment by rudeboybert** [comment]
Sounds like a plan, I'll email Jesse

**Comment by beanumber** [comment]
Nick also mentioned the possibility of [Datasets and Stories article for JSDSE](https://www.tandfonline.com/action/journalInformation?show=aimsScope&journalCode=ujse21)

**Comment by beanumber** [comment]
https://github.com/openjournals/joss/issues/1102
