### ISSUE TITLE
investigate duplicate readings

### ISSUE THREAD

**Issue by beanumber** [beanumber/macleish#8]
```
whately_2015 %>%
  group_by(when) %>%
  summarize(N = n()) %>%
  filter(N > 1)
Source: local data frame [6 x 2]

                 when     N
                (chr) (int)
1 2015-01-26 15:40:00     2
2 2015-03-16 19:40:00     2
3 2015-05-12 15:50:00     2
4 2015-09-16 07:30:00     2
5 2015-11-05 13:50:00     2
6 2015-11-20 15:00:00     2
```
Why? What is going on here? 

Are the entire rows duplicated? Or just the times? 

Is this important? Should the duplicates be dropped? Or averaged? Or left alone?

**Comment by vegahi** [comment]
The duplicates are the same. Maybe it's a recording error. The solution is to remove the duplicates from the dataset.

**Comment by beanumber** [comment]
Note that the duplicates are very strange -- it's not clear which ones are correct. 

```
whately_dec <- tbl(macleish, "whately") %>% collect() %>% mutate(when = as.POSIXct(when)) %>% filter(year(when) == 2012 & month(when) == 12 & day(when) >= 19 & day(when) <= 21)
ggplot(data = whately_dec, aes(x = when, y = Temp_C_Avg)) + geom_point() + geom_line()
```

**Comment by liwencong1995** [comment]
Paul sent me the original excel file that contains whatlyMet 10 min weather data, and the original files does not have any duplicate rows. Maybe we made some mistakes when we tried to convert "when" into the correct format.

**Comment by beanumber** [comment]
It appears that the time zone on the logging computer shifted from GMT to EST between 5:10 and 5:20 on 12/20/2012 for Whately. The data *after* this is in EST, but the data *before* that is in GMT and needs to be converted.

**Comment by liwencong1995** [comment]
```
whatelydata <- tbl(macleish, "whately")%>%
  collect() %>%
  mutate(num = seq(1, length.out=nrow(whatelydata), by=1)) %>%
  mutate(when = ifelse(num <= 50682, when - dhours(5), when)) %>%
  mutate(when = as.POSIXct(when, origin = "1970-01-01 10:00:00")) 
```
I added a new column called *num* (row number), and whenever num is < 50682, I subtract 5 hours from *when*, coz only the first 20682 rows had wrong time stamp.
