### ISSUE TITLE
investigate extremely cold temperatures for Orchard

### ISSUE THREAD

**Issue by beanumber** [beanumber/macleish#9]
```
orchard_2015 %>% filter(Temp_C_Avg < -30)
Source: local data frame [164 x 10]

                  when Temp_C_Avg WSpd_mps Wdir_deg RH_per_Avg Press_mb_Avg PAR_Den_Avg PAR_Tot_Avg
                 (chr)      (dbl)    (dbl)    (dbl)      (dbl)        (dbl)       (dbl)       (dbl)
1  2015-11-23 03:20:00     -38.09    0.589    265.7     13.250         1011       0.110       0.018
2  2015-11-23 03:30:00     -49.66    0.667    262.0      0.470         1011       0.000       0.000
3  2015-11-23 03:40:00     -67.48    0.787    253.7     -2.646         1011       0.192       0.031
4  2015-11-23 03:50:00     -71.34    0.829    249.6      8.670         1011       0.520       0.084
5  2015-11-23 15:20:00     -49.27    1.156    258.4      0.817         1015       1.642       0.265
6  2015-11-23 15:30:00     -48.50    1.021    264.5      1.568         1015       1.642       0.265
7  2015-11-23 15:40:00     -48.61    1.094    267.2      1.468         1015       1.506       0.243
8  2015-11-23 15:50:00     -48.48    0.908    264.9      1.574         1015       1.122       0.181
9  2015-11-23 16:00:00     -48.74    0.735    255.0      1.334         1015       0.849       0.137
10 2015-11-23 16:10:00     -49.33    0.449    262.9      0.754         1016       0.548       0.088
..                 ...        ...      ...      ...        ...          ...         ...         ...
Variables not shown: Rain_mm_Tot (dbl), the_year (chr)
```
Why is it so cold? Are these real readings? What is going on here? 

Should they be deleted? Or corrected? @vegahi wonders about multiple imputations?
Contact Paul Wetzel (CEEDS)

**Comment by nicholasjhorton** [comment]
You certainly calibrate using multiple imputation to a reference dataset (e.g., weather in Conway or Burgy).  That would let you compare to the observed temps and toss (or replace) the ones that are wildly wrong.

I'd be interested in hearing from Paul Wetzel about how such aberrant readings are handled in the literature.

Sounds like a good exercise for your data science class!

Nick

> On Mar 30, 2016, at 4:12 PM, Ben Baumer <notifications@github.com> wrote:
> 
> orchard_2015 %>% filter(Temp_C_Avg < -30)
> Source: local data frame [164 x 10]
> 
>                   when Temp_C_Avg WSpd_mps Wdir_deg RH_per_Avg Press_mb_Avg PAR_Den_Avg PAR_Tot_Avg
>                  (chr)      (dbl)    (dbl)    (dbl)      (dbl)        (dbl)       (dbl)       (dbl)
> 1  2015-11-23 03:20:00     -38.09    0.589    265.7     13.250         1011       0.110       0.018
> 2  2015-11-23 03:30:00     -49.66    0.667    262.0      0.470         1011       0.000       0.000
> 3  2015-11-23 03:40:00     -67.48    0.787    253.7     -2.646         1011       0.192       0.031
> 4  2015-11-23 03:50:00     -71.34    0.829    249.6      8.670         1011       0.520       0.084
> 5  2015-11-23 15:20:00     -49.27    1.156    258.4      0.817         1015       1.642       0.265
> 6  2015-11-23 15:30:00     -48.50    1.021    264.5      1.568         1015       1.642       0.265
> 7  2015-11-23 15:40:00     -48.61    1.094    267.2      1.468         1015       1.506       0.243
> 8  2015-11-23 15:50:00     -48.48    0.908    264.9      1.574         1015       1.122       0.181
> 9  2015-11-23 16:00:00     -48.74    0.735    255.0      1.334         1015       0.849       0.137
> 10 2015-11-23 16:10:00     -49.33    0.449    262.9      0.754         1016       0.548       0.088
> ..                 ...        ...      ...      ...        ...          ...         ...         ...
> Variables not shown: Rain_mm_Tot (dbl), the_year (chr)
> 
> Why is it so cold? Are these real readings? What is going on here?
> 
> Should they be deleted? Or corrected? @vegahi wonders about multiple imputations?
> Contact Paul Wetzel (CEEDS)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by liwencong1995** [comment]
According to Paul Wetzel, there was a loose wire connection on the temperature sensor that prevented the logger from receiving a signal and the default is for the logger to write -100 degrees.

**Comment by nicholasjhorton** [comment]
Are you planning to include two forms of this variable (one the original that came in through the system and the other some form of warning that the value is aberrant)?

Nick

> On Apr 6, 2016, at 3:55 PM, liwencong1995 <notifications@github.com> wrote:
> 
> According to Paul Wetzel, there was a loose wire connection on the temperature sensor that prevented the logger from receiving a signal and the default is for the logger to write -100 degrees.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by beanumber** [comment]
@nicholasjhorton look at these:
```
ggplot(data = orchard_2015, aes(x = when, y = Temp_C_Avg)) + geom_line()
densityplot(~Temp_C_Avg, data = orchard_2015)
```
Do you think adding a new column (e.g. `temp_corrected`) is the right solution?

**Comment by nicholasjhorton** [comment]
Would the values for temp_corrected be imputed using other data?  Or just listed as being missing?

Nick

> On Apr 7, 2016, at 10:25 AM, Ben Baumer <notifications@github.com> wrote:
> 
> @nicholasjhorton look at these:
> 
> ggplot(data = orchard_2015, aes(x = when, y = Temp_C_Avg)) + geom_line()
> densityplot(~Temp_C_Avg, data = orchard_2015)
> 
> Do you think adding a new column (e.g. temp_corrected) is the right solution?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by beanumber** [comment]
@nicholasjhorton you are the expert on such matters. There are only a few cases. I'm inclined to just leave them missing but I will defer to your judgement.

**Comment by nicholasjhorton** [comment]
Missing it is!

Nick

> On Apr 7, 2016, at 8:39 PM, Ben Baumer <notifications@github.com> wrote:
> 
> @nicholasjhorton you are the expert on such matters. There are only a few cases. I'm inclined to just leave them missing but I will defer to your judgement.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by beanumber** [comment]
I've added a note about this in the vignette and the documentation. I'm inclined to leave it as an exercise in imputation.
